server:
  port: 8866
  servlet:
    context-path: /JhrlPro
  tomcat:
    max-threads: 5000

master:
  datasource:
    url: jdbc:mysql://localhost:3306/snowtest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
    driverClassName: com.mysql.jdbc.Driver

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: /JhrlPro

